### PR TITLE
[lnn] fn selection fix

### LINKED ISSUE #599: fix function selection

### PR DESCRIPTION
**Pull request by cdmistman**
fixes #599 

I kept some debug output *in case* something happens but I don't expect any of them to actually print. Other than that the documentation should be pretty thorough and should in the end be more accurate than the current selection system. This system should also determine all types of values except for those that depend on the parameters of the function, which means that functions are fully type-checked (instead of only partially type-checked) before inlining, even if they're on the cold path (functions not used by any handler).

### CODE REVIEW

File: compiler/src/lnntoamm/Expr.ts [hunk 1]
```diff
@@ -356,16 +356,23 @@ export default abstract class Expr {
...
-            (fns, op) => [...fns, ...op.select(metadata.scope, applyTo.ty)],
-            new Array<Fn>(),
+          const [fns, retTys] = operators.reduce(
+            ([fns, retTys], op) => {
+              const [selFns, selTys] = op.select(metadata.scope, applyTo.ty);
+              fns = [...fns, ...selFns];
+              retTys = [...retTys, ...selTys];
+              return [fns, retTys];
+            },
+            [new Array<Fn>(), new Array<Type>()] as [Fn[], Type[]],
```
Comment (dfellis) [inline compiler/src/lnntoamm/Expr.ts:366]: What a failure of TS's type inference here...

File: compiler/src/lnntoamm/Expr.ts [hunk 2]
```diff
@@ -356,16 +356,23 @@ export default abstract class Expr {
...
           );
+          const retTy = Type.oneOf(retTys);
```
Comment (dfellis) [inline compiler/src/lnntoamm/Expr.ts:368]: Which one does `Type.oneOf` choose? Just the first, or something more complex?

File: compiler/src/lnntoamm/Expr.ts [hunk 3]
```diff
@@ -543,7 +565,9 @@ class Call extends Expr {
     }
     // first reduction
     const argTys = args.map((arg) => arg.ty);
-    fns = Fn.select(fns, argTys, metadata.scope);
+    const selFns = FunctionType.matrixSelect(fns, argTys, metadata.scope);
+    fns = selFns.map(([fn, _ty]) => fn);
```
Comment (dfellis) [inline compiler/src/lnntoamm/Expr.ts:569]: Nit: couldn't this just be `fns = selFns.map(selFn => selFn[0]);`

Doing function argument-level destructuring and assignment to an unused variable seems like a performance penalty that will affect interpreter mode heavily and may still trip up the JIT on being able to fully optimize back down to the form I wrote above?

File: compiler/src/lnntoamm/Expr.ts (hunk 2 above)
Comment (cdmistman) [reply compiler/src/lnntoamm/Expr.ts:368]: when `retTy.instance()` is called, it'll return the type furthest back in the list. that's to maintain the last-defined rule

File: compiler/src/lnntoamm/Expr.ts [hunk 4]
```diff
@@ -607,7 +654,9 @@ class Call extends Expr {
       console.log('expected output type:', ty);
       throw new Error(`no function selected`);
     }
-    const fn = selected.pop();
+    // Fn.select should implement the matrix so that the most reasonable
+    // choice is last in the fn array.
+    const fn = selFns.pop();
```
Comment (dfellis) [inline compiler/src/lnntoamm/Expr.ts:659]: Perhaps a warning mode might be worthwhile to allow users to know that the type was ambiguous and it's choosing from a list? "most reasonable" might not be what they're actually after and letting them know they should annotate their desired type seems like a good idea?

File: compiler/src/lnntoamm/Fn.ts [hunk 5]
```diff
@@ -41,6 +42,37 @@ export default class Fn {
     this.body = body;
     this.metadata =
       metadata !== null ? metadata : new MetaData(scope, this.retTy);
+    while (
+      this.body.reduce(
+        (carry, stmt) => stmt.cleanup(this.scope) || carry,
```
Comment (dfellis) [inline compiler/src/lnntoamm/Fn.ts:47]: So we are now having the min Node version be 14, so we could do this instead:

```suggestion
        (carry, stmt) => stmt.cleanup(this.scope) ?? carry,
```

File: compiler/src/lnntoamm/Expr.ts (hunk 4 above)
Comment (cdmistman) [reply compiler/src/lnntoamm/Expr.ts:659]: that's a good idea, but that'd have to wait for a future PR that focuses on better error handling throughout the compiler in general. the "most reasonable" wording has 2 meanings here: first, it prefers functions that are most specialized for the given argument types (for example, it picks `fn add(int64, int64)` over `fn add(int32, int32)` given raw literals, even if the latter was declared after the former since we prefer `int64` over `int32` in alan - this really only means that it impacts such cases). The other meaning is that it still maintains order of definition, so the last-defined function is given higher precedence over the first-defined function, even if both have the same function signature.

The comment is slightly outdated (I made it in one of the earlier commits before I moved the matrix selection to `Types.ts`) so I'll update it and add clarity

File: compiler/src/lnntoamm/Types.ts [hunk 6]
```diff
@@ -242,6 +246,162 @@ class Builtin extends Type {
...
+        }, new Array<[Fn, Type]>()),
+      );
+      fnsByWeight.set(weight, fnsForWeight);
+      if (
+        indices.every(
+          (idxInDim, dimIdx) => idxInDim === matrix[dimIdx].length - 1,
+        )
+      ) {
+        break;
+      }
```
Comment (dfellis) [inline compiler/src/lnntoamm/Types.ts:309]: Is this conditional guaranteed to always eventually execute? Otherwise this for loop can potentially infinite loop.

File: compiler/src/lnntoamm/Fn.ts (hunk 5 above)
Comment (cdmistman) [reply compiler/src/lnntoamm/Fn.ts:47]: the carry is a boolean though, so I think it's slightly more readable to keep it as `||`

File: compiler/src/lnntoamm/Types.ts [hunk 7]
```diff
@@ -242,6 +246,162 @@ class Builtin extends Type {
...
+      weightFns = weightFns.filter(
+        ([weightedFn, _retTy]) =>
+          fns.findIndex(([fn, _retTy]) => fn === weightedFn) === -1,
+      );
+      return [...fns, ...weightFns];
+    }, new Array<[Fn, Type]>());
+    if (ret.length > originalLength) {
+      console.log('~~~ ERROR');
+      console.log('original:', originalLength);
+      console.log('retLengt:', ret.length);
```
Comment (dfellis) [inline compiler/src/lnntoamm/Types.ts:338]:
```suggestion
      console.log('retLength:', ret.length);
```

File: compiler/src/lnntoamm/Types.ts [hunk 8]
```diff
@@ -242,6 +246,162 @@ class Builtin extends Type {
...
+    } else if (ty instanceof OneOf || ty instanceof Generated) {
+      return ty.compatibleWithConstraint(this, scope);
+    } else {
+      return false;
+    }
+  }
+
+  constrain(to: Type, scope: Scope): void {
+    console.log(to);
+    TODO('figure out what it means to constrain a function type');
```
Comment (dfellis) [inline compiler/src/lnntoamm/Types.ts:366]: Probably similar to how generic types would be constrained? You could treat function types like `Fn<A, R>` with A being the arg types and R being the return type, and then either also implement variadic generic types or just hardwire something like `Arg0`, `Arg1<A>`, `Arg2<A, B>`, ... to some large-ish maximum arg length.

Those simple generics could themselves be generated in the code and never exposed to the user so it wouldn't be *too* crazy to go up to something like `Arg99` if that is possible.

File: compiler/src/lnntoamm/Types.ts (hunk 6 above)
Comment (cdmistman) [reply compiler/src/lnntoamm/Types.ts:309]: yes. the index iteration is similar to how normal addition is performed. 

Say dimension 0 (using 0-indexing since that's how the `matrix` var works) has 2 elements, dimension 1 has 1 element, and dimension 2 has 2 elements. The first loop run would be `indices=[0,0,0]`. the `reduceRight` on the next line performs the addition-like iteration, resulting in `indices=[0,0,1]`. On the next loop, it's `indices=[1,0,0]` because of the carry skipping dimension 1. After this `if` check gets performed, it performs the final addition to get `indices=[1,0,1]` but must go to the beginning of the loop to calculate weight, etc before finally passing this `if` check and `break`ing

**Review by dfellis — APPROVED** [review]

File: compiler/src/lnntoamm/Types.ts (hunk 8 above)
Comment (cdmistman) [reply compiler/src/lnntoamm/Types.ts:366]: right, but I'm waiting until I tackle #534 before I figure this out, since there aren't any cases where `FunctionType.constrain` is called (unless there's some weird bug)

File: compiler/src/lnntoamm/Expr.ts (hunk 4 above)
Comment (dfellis) [reply compiler/src/lnntoamm/Expr.ts:659]: Yeah, no problem, just pointing out that this is a good place for eventually adding a warning that the compiler could emit and also maybe a fail-on-warning mode check if we want that, too.

File: compiler/src/lnntoamm/Fn.ts (hunk 5 above)
Comment (dfellis) [reply compiler/src/lnntoamm/Fn.ts:47]: Ahh, I thought you were replacing a null-ish result from `cleanup` when I first wrote this. Keeping it as `||` is actually correct and `??` would break it.

File: compiler/src/lnntoamm/Expr.ts (hunk 1 above)
Comment (cdmistman) [reply compiler/src/lnntoamm/Expr.ts:366]: er, it does work without the `as` but it wasn't in a previous commit. removing the `as`

**Review by dfellis — APPROVED** [review]

**Review by depombo — APPROVED** [review]
